#!/bin/sh
#sudo iptables -t raw -A PREROUTING -i wlan0 -j NFQUEUE --queue-num 0
#sudo iptables -t raw -A OUTPUT -o wlan0 -j NFQUEUE --queue-num 0
sudo iptables -t mangle -A FORWARD -o wlan0 -p tcp -d 192.168.69.139 -j NFQUEUE --queue-num 0
sudo iptables -t mangle -A FORWARD -o wlan0 -p tcp -d 192.168.69.67 -j NFQUEUE --queue-num 1
